# Generated by Django 2.2.6 on 2019-10-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='essay',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='essays_upload'),
        ),
        migrations.AddField(
            model_name='essay',
            name='img_source',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='essay',
            name='essay_source',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='parsing_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
