# Generated by Django 2.2.6 on 2019-10-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191015_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='essay',
            options={'verbose_name': 'Essay', 'verbose_name_plural': 'Essays'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='essay',
            name='essay_source',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
