# Generated by Django 2.2.6 on 2019-10-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='moderted',
            new_name='moderated',
        ),
        migrations.AddField(
            model_name='review',
            name='essay',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Essay'),
            preserve_default=False,
        ),
    ]
